### PR TITLE
Firefox support

### PR DESCRIPTION
**Pull request by Absolucy**
Still works on Chrome.

### CODE REVIEW

**Comment by flleeppyy** [comment]
woahhhh hell yeah

**Review by flleeppyy — APPROVED** [review]

**Comment by flleeppyy** [comment]
wait a minute are you *sure* this works? It actually doesn't work and tells me its corrupt.

**Comment by Absolucy** [comment]
it worked for me?

**Comment by Absolucy** [comment]
image

**Comment by flleeppyy** [comment]
image

**Comment by up201306506** [comment]
A change like this woldn't work for firefox regardless, because the way the replace.js is detecting a NFT avatar is through the aria-label property of some containers. And Firefox doesn't support Element.ariaLabel.

https://developer.mozilla.org/en-US/docs/Web/API/Element/ariaLabel

**Comment by Absolucy** [comment]
@up201306506 ... it literally worked for me in firefox. as in, I tested it on twitter.

**Comment by Vendicated** [comment]
Firefox indeed doesn't support ariaLabel. The reason it works on firefox regardless is that the fork still uses the old version with querySelectorAll. 

Something like this should do the trick
```js
[...document.querySelectorAll('div[aria-label*="NFT"]')].filter(node => !node.hasAttribute("role"))
```

image

**Comment by rachelnicole** [comment]
you also have to change the code to use `browser.` instead of `chrome.` and turn the event handling into promises, i added an issue with inconsistencies across vendors.

**Comment by flleeppyy** [comment]
Hm, the API's are roughly the same from my knowledge, couldn't you just declare a constant variable like `const browserApi = browser || chrome`? I've never worked on extensions/addons before so I don't know if this is recommended

**Comment by rachelnicole** [comment]
> Hm, the API's are roughly the same from my knowledge, couldn't you just declare a constant variable like `const browserApi = browser || chrome`? I've never worked on extensions/addons before so I don't know if this is recommended

you could, but you'd still have to cover the event handling as well. (see 'Callbacks and Promises' here: [Chrome Incompatibilities](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Chrome_incompatibilities) Or you could just write it once for firefox's standards and use the polyfill to cover the rest.

**Pull request closed without merging**
